### ISSUE TITLE
Running `tail -f` from remote_task

### ISSUE THREAD

**Issue by arr-dev** [seattlerb/rake-remote_task#22]
I have task defined as follows:
```rb
remote_task 'vlad:tail' do
  old_flags = ssh_flags
  set :ssh_flags, %w(-t)

  run "tail -f #{shared_path}/log/*.log"

  set :ssh_flags, old_flags
end
```

However, even though I added `-t` to `ssh_flags` after `Ctrl+C`'ing the task, `tail` command remains running on the server.

Same thing doesn't happen when running plain ssh command with `ssh -t server tail -f shared_path/log/*.log`.

What am I missing?

**Comment by zenspider** [comment]
I think this is dead. Closing. Feel free to reopen if you feel it isn't.
